// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | BigTextSlice
  | AlternatingTextSlice
  | CarouseSlice
  | SkyDiveSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *AlternatingText → Default → Primary → Text Group*
 */
export interface AlternatingTextSliceDefaultPrimaryTextGroupItem {
  /**
   * Heading field in *AlternatingText → Default → Primary → Text Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternating_text.default.primary.text_group[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *AlternatingText → Default → Primary → Text Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternating_text.default.primary.text_group[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *AlternatingText → Default → Primary*
 */
export interface AlternatingTextSliceDefaultPrimary {
  /**
   * Text Group field in *AlternatingText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternating_text.default.primary.text_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  text_group: prismic.GroupField<
    Simplify<AlternatingTextSliceDefaultPrimaryTextGroupItem>
  >;
}

/**
 * Default variation for AlternatingText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternatingTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternatingTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlternatingText*
 */
type AlternatingTextSliceVariation = AlternatingTextSliceDefault;

/**
 * AlternatingText Shared Slice
 *
 * - **API ID**: `alternating_text`
 * - **Description**: AlternatingText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternatingTextSlice = prismic.SharedSlice<
  "alternating_text",
  AlternatingTextSliceVariation
>;

/**
 * Default variation for BigText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BigText*
 */
type BigTextSliceVariation = BigTextSliceDefault;

/**
 * BigText Shared Slice
 *
 * - **API ID**: `big_text`
 * - **Description**: BigText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSlice = prismic.SharedSlice<
  "big_text",
  BigTextSliceVariation
>;

/**
 * Primary content in *Carouse → Default → Primary*
 */
export interface CarouseSliceDefaultPrimary {
  /**
   * Heading field in *Carouse → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carouse.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Price Copy field in *Carouse → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carouse.default.primary.price_copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price_copy: prismic.RichTextField;
}

/**
 * Default variation for Carouse Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carouse*
 */
type CarouseSliceVariation = CarouseSliceDefault;

/**
 * Carouse Shared Slice
 *
 * - **API ID**: `carouse`
 * - **Description**: Carouse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouseSlice = prismic.SharedSlice<
  "carouse",
  CarouseSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Cans Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.cans_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cans_image: prismic.ImageField<never>;

  /**
   * Second Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_heading: prismic.TitleField;

  /**
   * Second Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.second_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_body: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SkyDive → Default → Primary*
 */
export interface SkyDiveSliceDefaultPrimary {
  /**
   * Sentence field in *SkyDive → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sky_dive.default.primary.sentence
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sentence: prismic.KeyTextField;

  /**
   * Flavour field in *SkyDive → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: sky_dive.default.primary.flavour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  flavour: prismic.SelectField<
    "lemonLime" | "grape" | "blackCherry" | "strawberryLemonade" | "watermelon"
  >;
}

/**
 * Default variation for SkyDive Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkyDiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkyDiveSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SkyDive*
 */
type SkyDiveSliceVariation = SkyDiveSliceDefault;

/**
 * SkyDive Shared Slice
 *
 * - **API ID**: `sky_dive`
 * - **Description**: SkyDive
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkyDiveSlice = prismic.SharedSlice<
  "sky_dive",
  SkyDiveSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternatingTextSlice,
      AlternatingTextSliceDefaultPrimaryTextGroupItem,
      AlternatingTextSliceDefaultPrimary,
      AlternatingTextSliceVariation,
      AlternatingTextSliceDefault,
      BigTextSlice,
      BigTextSliceVariation,
      BigTextSliceDefault,
      CarouseSlice,
      CarouseSliceDefaultPrimary,
      CarouseSliceVariation,
      CarouseSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SkyDiveSlice,
      SkyDiveSliceDefaultPrimary,
      SkyDiveSliceVariation,
      SkyDiveSliceDefault,
    };
  }
}
